// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mih_add_ContactDate_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mih_add_ContactDate_class));
        
        string IMigrationMetadata.Id
        {
            get { return "202204240317468_mih_add_ContactDate_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
